default: &default
   adapter: postgresql
   encoding: unicode
  
development:
   adapter: postgresql
   encoding: unicode
   database: Rubyon_Rails_development
   username: postgres
   password: 66612345

test:
   adapter: postgresql
   encoding: unicode
   database: Rubyon_Rails_test
   username: postgres
   password: 66612345
 
production:
   adapter: postgresql
   encoding: unicode
   database: Rubyon_Rails_production
   username: postgres
   password: 66612345